_extends: kaskada:.github/release-drafter.yml

name-template: Engine $RESOLVED_VERSION
tag-template: engine@v$RESOLVED_VERSION
tag-prefix: engine@v

# Only include PRs with one of these labels
include-labels:
  - sparrow
  - wren
  - proto