apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kaskada-canary-db
  namespace: {{ include "kaskada-canary.namespace" . }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.dbData.storage }}
  storageClassName: {{ .Values.storage.dbData.storageClassName }}
  volumeMode: Filesystem
