{{- if (eq .Values.storage.objectStore.type "s3") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kaskada-canary.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kaskada-canary.labels" . | nindent 4 }}
data:
  AWS_ACCESS_KEY_ID: {{ tpl .Values.storage.objectStore.s3.accessKeyId $ | b64enc | quote  }}
  AWS_SECRET_ACCESS_KEY: {{  tpl .Values.storage.objectStore.s3.secretAccessKey $ | b64enc | quote }}
{{- end }}
