tables:
  - config:
      name: Transaction
      uuid: ece50bec-9cdb-11ed-a8fc-0242ac120002
      time_column_name: transaction_date
      group_column_name: msno
      grouping: Transaction
    metadata:
      file_count: 1
      schema:
        fields:
          - name: msno
            data_type:
              kind: !Primitive 14 # STRING
          - name: payment_method_id
            data_type:
              kind: !Primitive 6 # I64
          - name: payment_plan_days
            data_type:
              kind: !Primitive 6 # I64
          - name: transaction_date
            data_type:
              kind: !Primitive 6 # I64
          - name: membership_expire_date
            data_type:
              kind: !Primitive 6 # I64
    file_sets:
      - slice_plan:
          table_name: Transaction
          percent: 100
        prepared_files:
          - path: prepared/prepared-Transaction-transactions-0.parquet
            min_event_time: 1970-01-01T00:00:00.020150101Z
            max_event_time: 1970-01-01T00:00:00.020170228Z
            num_rows: 1000000
            metadata_path: prepared/prepared-Transaction-transactions-0-metadata.parquet
          - path: prepared/prepared-Transaction-transactions-1.parquet
            min_event_time: 1970-01-01T00:00:00.020150101Z
            max_event_time: 1970-01-01T00:00:00.020170228Z
            num_rows: 1000000
            metadata_path: prepared/prepared-Transaction-transactions-1-metadata.parquet
          - path: prepared/prepared-Transaction-transactions-2.parquet
            min_event_time: 1970-01-01T00:00:00.020150101Z
            max_event_time: 1970-01-01T00:00:00.020170228Z
            num_rows: 1000000
            metadata_path: prepared/prepared-Transaction-transactions-2-metadata.parquet