{{- if .Values.secretConfiguration.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kaskada.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kaskada.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.secretConfiguration.data }}
  {{ $key }}: {{ tpl $value $ | b64enc | quote }}
{{- end }}
{{- end }}
