# Default values for kaskada-canaray.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Overrides the chart's name
nameOverride: ""

# -- Overrides the chart's computed fullname
fullnameOverride: ""

namespace:
  # -- The name of the Namespace to deploy
  # If not set, `.Release.Namespace` is used
  name: null

# -- Image pull secrets for Docker images
imagePullSecrets: []

image:
  # -- Docker image repository
  repository: ghcr.io/kaskada-ai/engine
  # -- Overrides the image tag whose default is the chart's appVersion
  tag: v0.4.1
  # -- Docker image pull policy
  pullPolicy: IfNotPresent

# -- Common annotations for all pods
podAnnotations: {}

# -- Common labels for all pods
podLabels: {}

# -- The number of old ReplicaSets to retain to allow rollback
revisionHistoryLimit: 10

## Expose the kaskada-canary service to be accessed from outside the cluster (LoadBalancer service).
## or access it from within the cluster (ClusterIP service). Set the service type and the port to serve it.
## ref: http://kubernetes.io/docs/user-guide/services/
##
service:
  enabled: true
  type: ClusterIP
  grpcPort: 50051
  restPort: 3365
  ## Service annotations. Can be templated.
  annotations: {}
  labels: {}
  # Adds the appProtocol field to the service. This allows to work with istio protocol selection. Ex: "http" or "tcp"
  appProtocol: ""

serviceAccount:
  # -- Specifies whether a ServiceAccount should be created
  create: true
  # -- The name of the ServiceAccount to use.
  # If not set and create is true, a name is generated using the fullname template
  name: null
  # -- Image pull secrets for the service account
  imagePullSecrets: []
  # -- Annotations for the service account
  annotations: {}
  # -- Set this toggle to false to opt out of automounting API credentials for the service account
  automountServiceAccountToken: true


extraEnv: []
# -- Environment variables from secrets or configmaps to add to the canary pods
extraEnvFrom: []
# -- Resource requests and limits for the canary
resources: {}


# -- Volume mounts to add to the containers
extraVolumeMounts: []
# -- Volumes to add to the containers
extraVolumes: []

# labels to apply to all resources
commonLabels: {}

affinity: {}
# -- Node selector for canary pods
nodeSelector: {}
# -- Tolerations for canary pods
tolerations: []

engineResources:
  limits:
    cpu: 2
    memory: 8Gi
  requests:
    cpu: 500m
    memory: 2Gi

managerResources:
  limits:
    cpu: 250m
    memory: 250Mi
  requests:
    cpu: 100m
    memory: 100Mi


logLevel: info
logFormat: json

secretConfiguration:
  enabled: false
  mountPath: ""
  subPath: ""
  data: {}
    # credentials: |
    #   [default]
    #   aws_access_key_id = $SECRET_ACCESS_KEY
    #   aws_secret_access_key = $SECRET_ACCESS_KEY

deploymentStrategy:
  type: Recreate
