on:
  workflow_call:
  workflow_dispatch:

permissions:
  # For deploying release artifacts.
  contents: write
  pull-requests: read
  # For pushing Docker images to ghcr.io.
  packages: write
  # For creating the release announcement.
  discussions: write

name: Build linux/aarch64

jobs:
  sparrow_cross_amd64_arm64:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Current Date
        id: current_date
        run: |
          echo "created=$(date -u +"%Y-%m-%d %H:%M:%S%z")" | tee -a "$GITHUB_OUTPUT"
        shell: bash

      - name: Install stable toolchain
        id: toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy
          targets: aarch64-unknown-linux-gnu

      - name: Apt Packages (Linux)
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: lld
          version: 1.0

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install cross
        shell: bash
        run: cargo install cross 

      - name: Sparrow - cross build (Release)
        shell: bash
        run: |
          cross  build --release --all-features --target aarch64-unknown-linux-gnu -p sparrow-main

      - name: Upload engine artifacts
        uses: actions/upload-artifact@v3
        with:
          name: engine-linux-aarch64
          retention-days: 5
          path: |
            target/aarch64-unknown-linux-gnu/release/sparrow-main